spring.application.name=eureka-server
server.port=8761

# Ne pas s'enregistrer soi-même dans Eureka (on EST le serveur)
eureka.client.register-with-eureka=false
# Ne pas récupérer le registre localement (on est le serveur, on est le registre)
eureka.client.fetch-registry=false

# URL de l'instance Eureka
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

# Logs
logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN
