server:
  port: 8085

spring:
  application:
    name: followup-alert-service
  datasource:
    url: jdbc:mysql://localhost:3306/followup_alert_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    enabled: false