spring.application.name=traitement_et_consultation
server.port=8081


spring.datasource.url=jdbc:mysql://localhost:3306/alzheimer_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.serialization.write-dates-as-timestamps=false
spring.docker.compose.enabled=false
# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Email properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=razinamanath@gmail.com
spring.mail.password=eici pecd fypx phya
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
