spring.application.name=users_service
<<<<<<< HEAD
=======
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/alzheimer_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.serialization.write-dates-as-timestamps=false
spring.docker.compose.enabled=false
# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
>>>>>>> 42bf8ed763718cbe3c0892baab9e519ea11d2c32
